version: "3.8"

services:
    # bbdd postgresql
    db_postgres:
        image: postgres:alpine3.19
        container_name: alpes_postgres_db
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: alpes_bank_db
            POSTGRES_USER: postgres
            POSTGRES_PORT: 5432
        ports:
            - "5432:5432"
        # volumes:
            # - ./data:/var/lib/postgresql/data
            

    # fastapi app
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"


