version: '3.8'
services:
  db:
    image: postgres:13
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
