version: "3.8"

services:
  db:
    image: postgres:13
    container_name: alpes_postgres_db
    environment:
      POSTGRES_DB: alpes_bank_db
      POSTGRES_USER: alpes_user
      POSTGRES_PASSWORD: alpes_password
    ports:
      - "5432:5432"

