"""update user schema

Revision ID: c83685a2bce2
Revises: 55a6299c43e5
Create Date: 2024-03-16 11:13:13.090892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83685a2bce2'
down_revision: Union[str, None] = '55a6299c43e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ingresos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ingresos')
    # ### end Alembic commands ###