name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Docker configure
      run: gcloud auth configure-docker 

    - name: Build Docker image
      run: docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:${{ github.sha }} .

    

    - name: Push Docker image
      run: docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:${{ github.sha}}


    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/fastapi-app fastapi-app=gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-app:${{ github.sha }}
